package tripit

// This file was generated by a tool. Do not edit.

import (
	"encoding/json"
)

// GroupVector is a specialization of Vector for Group objects.
type GroupVector []Group

// UnmarshalJSON builds the vector from the JSON in b.
func (p *GroupVector) UnmarshalJSON(b []byte) error {
	var arr *[]Group
	arr = (*[]Group)(p)
	*arr = nil
	err := json.Unmarshal(b, arr)
	if err != nil {
		*arr = make([]Group, 1)
		err := json.Unmarshal(b, &(*arr)[0])
		if err != nil {
			if err2, ok := err.(*json.UnmarshalTypeError); ok && err2.Value == "null" {
				*arr = (*arr)[0:0]
			} else {
				return err
			}
		}
		
	}
	return nil
}
