package tripit

// This file was generated by a tool. Do not edit.

import (
	"encoding/json"
)

// A specialization of Vector for PointsProgramActivity objects
type PointsProgramActivityVector []PointsProgramActivity

func (p *PointsProgramActivityVector) UnmarshalJSON(b []byte) error {
	var arr *[]PointsProgramActivity
	arr = (*[]PointsProgramActivity)(p)
	*arr = nil
	err := json.Unmarshal(b, arr)
	if err != nil {
		*arr = make([]PointsProgramActivity, 1)
		err := json.Unmarshal(b, &(*arr)[0])
		if err != nil {
			if err2, ok := err.(*json.UnmarshalTypeError); ok && err2.Value == "null" {
				*arr = (*arr)[0:0]
			} else {
				return err
			}
		}

	}
	return nil
}
