package tripit

// This file was generated by a tool. Do not edit.

import (
	"encoding/json"
)

// PointsProgramVector is a specialization of Vector for PointsProgram objects.
type PointsProgramVector []PointsProgram

// UnmarshalJSON builds the vector from the JSON in b.
func (p *PointsProgramVector) UnmarshalJSON(b []byte) error {
	var arr *[]PointsProgram
	arr = (*[]PointsProgram)(p)
	*arr = nil
	err := json.Unmarshal(b, arr)
	if err != nil {
		*arr = make([]PointsProgram, 1)
		err := json.Unmarshal(b, &(*arr)[0])
		if err != nil {
			if err2, ok := err.(*json.UnmarshalTypeError); ok && err2.Value == "null" {
				*arr = (*arr)[0:0]
			} else {
				return err
			}
		}
		
	}
	return nil
}
