package main

func getTemplate() string {
	return `package {{.Package}}

// This file was generated by a tool. Do not edit.

import (
	"os"
	"json"
)

// A specialization of Vector for {{.Type}} objects
type {{.Name}}Vector []{{.Type}}

func (p *{{.Name}}Vector) UnmarshalJSON(b []byte) os.Error {
	var arr *[]{{.Type}}
	arr = (*[]{{.Type}})(p)
	*arr = nil
	err := json.Unmarshal(b, arr)
	if err != nil {
		*arr = make([]{{.Type}}, 1)
		err := json.Unmarshal(b, &(*arr)[0])
		if err != nil {
			if err2, ok := err.(*json.UnmarshalTypeError); ok && err2.Value == "null" {
				*arr = (*arr)[0:0]
			} else {
				return err
			}
		}
		{{if .IsPtr}}
		if (*arr)[0] == nil {
			*arr = (*arr)[0:0]
		}
		{{end}}
	}
	return nil
}
`
}
